In [1]:
import numpy as np

In [2]:
a = np.array([2, 4, 6, 8, 10])
b = np.array([[2, 4, 6], [8, 10, 12]])
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [3]:
print("Size:")
print(a.size)
print(b.size)
print(c.size)

print("\nNumber of dimensions:")
print(a.ndim)
print(b.ndim)
print(c.ndim)

Size:
5
6
8

Number of dimensions:
1
2
3


In [4]:
print("Shape of a:", a.shape)
print("After reshape:")
print(a.reshape(1, 5))

Shape of a: (5,)
After reshape:
[[ 2  4  6  8 10]]


In [5]:
a2 = a.copy()
print("Original:", a)
print("Copy:", a2)

Original: [ 2  4  6  8 10]
Copy: [ 2  4  6  8 10]


In [6]:
flat = b.ravel()
print("Ravel:", flat)
flat[1] = 20
print("After changing one value:", flat)

Ravel: [ 2  4  6  8 10 12]
After changing one value: [ 2 20  6  8 10 12]


In [7]:
print("Total:", a.sum())
print("Row totals:", b.sum(axis=1))

Total: 30
Row totals: [28 30]


In [8]:
print("Broadcasting:")
print(a + 5)

Broadcasting:
[ 7  9 11 13 15]


In [9]:
print("Values greater than 5:")
print(a[a > 5])

Values greater than 5:
[ 6  8 10]


In [10]:
print("Positions where value is greater than 5:")
print(np.where(a > 5))

Positions where value is greater than 5:
(array([2, 3, 4]),)


In [11]:
marks = np.array([55, 72, 91, 38, 64, 84, 29, 76, 48, 95])

grade = np.select(
    [marks >= 90, marks >= 70, marks >= 50, marks >= 33],
    ["A", "B", "C", "D"],
    default="F"
)

for i in range(len(marks)):
    print("Mark:", marks[i], "Grade:", grade[i])

Mark: 55 Grade: C
Mark: 72 Grade: B
Mark: 91 Grade: A
Mark: 38 Grade: D
Mark: 64 Grade: C
Mark: 84 Grade: B
Mark: 29 Grade: F
Mark: 76 Grade: B
Mark: 48 Grade: D
Mark: 95 Grade: A
